/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Y8B314fwUbN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function CreditForm() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Enter Payment Details</CardTitle>
        <CardDescription>Securely enter your credit card information to complete your purchase.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="cardNumber">Card Number</Label>
          <Input
            id="cardNumber"
            pattern="&quot;d{16}&quot;"
            placeholder="0000 0000 0000 0000"
            required
            title="Please enter a valid 16-digit card number"
            type="text"
          />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="expirationDate">Expiration Date</Label>
            <div className="grid grid-cols-2 gap-2">
              <Select required>
                <SelectTrigger>
                  <SelectValue placeholder="MM" />
                </SelectTrigger>
                <SelectContent />
              </Select>
              <Select required>
                <SelectTrigger>
                  <SelectValue placeholder="YYYY" />
                </SelectTrigger>
                <SelectContent />
              </Select>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="cvv">CVV</Label>
            <Input
              id="cvv"
              pattern="&quot;d{3}&quot;"
              placeholder="123"
              required
              title="Please enter a valid 3-digit CVV code"
              type="text"
            />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="cardholderName">Cardholder Name</Label>
          <Input id="cardholderName" placeholder="John Doe" required type="text" />
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto" type="submit">
          Pay Now
        </Button>
      </CardFooter>
    </Card>
  )
}
